# Generated by Django 2.2.12 on 2020-05-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='shoppingList',
            field=models.BooleanField(default=False),
        ),
    ]
